### PR TITLE
Hard-coded analytics setup

### PR DESCRIPTION
**Pull request by ericronne**
@gemfarmer's work!

We did an end run and dropped the google analytics code directly into the home.html and default.html files.

To be revisited at some point: debug issues with drawing data from the site object.

### CODE REVIEW

**Comment by ericronne** [comment]
[Set up google analytics on current site, for baseline stats](https://trello.com/c/oBL5M3wi/34-set-up-google-analytics-on-current-site-for-baseline-stats)

**Comment by stvnrlly** [comment]
With this approach, should the setting also be removed from `_config.yml`?

**Comment by ericronne** [comment]
Yeah i would think so. Hold pls …

**Comment by ericronne** [comment]
👍 @stvnrlly?

**Review by gemfarmer — APPROVED** [review]
Awesome! Glad it is working :)

**Review by stvnrlly — APPROVED** [review]

**Pull request merged**
